### ISSUE TITLE
Nontracked branches

### ISSUE THREAD

**Issue by particleflux** [deadc0de6/gitell#1]
Branches without a tracked remote produce ugly error messages:

```
Could not find a tracked remote branch, please specify <upstream> manually.
usage: git cherry [-v] [<upstream> [<head> [<limit>]]]

    --abbrev[=<n>]   use <n> digits to display SHA-1s
    -v, --verbose         be verbose
```

Should probably just mark them as _not in sync_?

Using git version: 2.16.1

**Comment by deadc0de6** [comment]
Thanks for reporting this.
I pushed a fix that should return *not in sync* when a branch doesn't track a remote.

**Comment by particleflux** [comment]
Can confirm it is fixed. Thanks!

**Comment by deadc0de6** [comment]
cool :+1:

**Comment by deadc0de6** [comment]
Well actually this is not optimal as I noticed some huge slowdowns with the new version.
I'll look into that to come up with a more optimized version.

**Comment by deadc0de6** [comment]
Ok I fixed it, it should now be much faster with the new version.
Thanks again!
